name: La Costa Cocina Menu
title: La Costa Cocina Menu
description: Digital menu for La Costa Cocina restaurant
baseurl: "/lacostacocina"
url: "https://edwinjlagoa-hub.github.io"

# Build settings
markdown: kramdown
exclude:
  - .git/
  - .github/
  - README.md